spring:
  application:
    name: CarRenting
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
#  datasource:
#    url: jdbc:postgresql://localhost:5432/car_renting
#    username: kent
#    password: kent
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/

